accounts/urls.py
from .views import *
from django.conf.urls import url

app_name = 'accounts'

urlpatterns = [
    url(r'^login/$', login_view, name='login'),
    url(r'^logout/$', logout_view, name='logout'),
    url(r'^register/$', register_view, name='register'),
]

blog/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.urls import path
from home.views import home_view
from selena.views import view_404


urlpatterns = [
    path('admin/', admin.site.urls),
    # url(r'^selena/', selena_view, name='selena'),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^selena/', include('selena.urls')),
    url(r'^$', home_view, name='home'),
    #path('', home_view)
    url(r'^.*/$', view_404)
]

selena/urls.py
from .views import selena_view, selena_view1, selena_view2, selena_save, selena_delete
from django.conf.urls import url

app_name = 'selena'

urlpatterns = [
    url(r'^selenareg/$', selena_view, name='selenareg'),
    url(r'^selenaunreg/$', selena_view1, name='selenaunreg'),
    url(r'^selenagone/$', selena_view2, name='selenagone'),
    url(r'^selenasave/$', selena_save, name='selenasave'),
    url(r'^selenadelete/$', selena_delete, name='selenadelete'),
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render
from django.contrib import messages


def home_view(request):
    client_address = request.META.get('REMOTE_ADDR')
    print ('  Site checked by : '+client_address)
    if request.user.is_authenticated:
        context = {
            'isim': request.user.username
        }
        messages.success(request, 'EDGE-CORE VƏ RAİSECOM SWITCH-LƏRİ QEYDİYYATLI USERLƏR YOXLAYA BİLƏRLƏR.')
    else:
        context = {
            'isim': ''
        }
        messages.success(request, 'EDGE-CORE VƏ RAİSECOM SWITCH-LƏRİ QEYDİYYATLI USERLƏR YOXLAYA BİLƏRLƏR.')
    return render(request, 'home.html', context)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" name="viewport" content="width=device-width, inital-scale=1">
    <title>{%block title%}'XXX' MMC{%endblock%}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    {% include 'header.html' %}


    {% block body %}

    {% endblock %}

    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

templates/header.html
<nav class="navbar navbar-inverse navbar-fixed-top" role="banner">
    <div class="container">
        <div class="navbar-header">
            <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <ul>
                {% if request.user.is_authenticated %}
                    <a href="/admin" class="btn btn-warning" role="button">Only Admin</a>
                    <a href="{% url 'home' %}" class="navbar-brand" role="button">İstifadəçi:{{ user.get_username }}</a>
                {% else %}
                    <a href="/admin" class="btn btn-warning" role="button">Only Admin</a>
                    <a href="{% url 'home' %}" class="navbar-brand" role="button">XXX LOGO</a>
                {% endif %}
            </ul>
        </div>
        <nav class="collapse navbar-collapse" role="navigation">  
            <ul class="nav navbar-nav navbar-right">
                {% if not request.user.is_authenticated %}
                    <li><a href="{% url 'selena:selenaunreg' %}">Qeydiyyatsız Yoxlanış</a></li>
                    <li><a href="{% url 'accounts:login' %}">Giriş</a></li>
                    <li><a href="{% url 'accounts:register' %}">Qeydiyyat</a></li>
                {% else%}
                    <li><a href="{% url 'selena:selenareg' %}">Yoxlanış</a></li>
                    <li><a href="{% url 'selena:selenagone' %}">Sürət verilməsi</a></li>
                    <li><a href="{% url 'accounts:logout' %}" class="btn btn-danger" role="button">Çıxış</a></li>
                {% endif %}
            </ul>
        </nav>
    </div>
</nav>

templates/home.html
{% extends 'base.html' %}

{% block title %}
{% load static %}
Ana Səhifə - {{block.super}}
{% endblock%}

{% block body %}

    <style>
        body {
            background-size: cover;
            background-repeat: no-repeat;
            background-image: url("{% static "img/city.gif" %}");
        }
    </style>

    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-success alert-dismissible" role="alert">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <strong>{{ message }}</strong>
                        </div>
                    {% endfor %}
                {% endif %}
                <h1 style="color:rgb(236, 238, 118)"; class="mt-5">Xoş gəlmişsiniz!</h1>
                <p style="color:rgb(236, 238, 118)"; class="lead">Saytda hər hansı çətinliklə qarşılaşdıqda bunu bildirməyiniz xahiş olunur</p>
                <p style="color:rgb(236, 238, 118)"; class="lead">Sayt, iki ssenari üzrə işləyir</p>
                <p style="color:rgb(236, 238, 118)"; class="lead">Qeydiyyatlı: Nömrəni qeyd etməklə yoxlama || Qeyd:'Billing' hesabı tələb olunur</p>
                <p style="color:rgb(236, 238, 118)"; class="lead">Qeydiyyatsız: Dslam, Plata və Port göstəricilərini qeyd etməklə yoxlama</p>
                <p style="color:rgb(236, 238, 118)"; class="lead">İşiniz bitdikdən sonra hesabınızdan 'Çıxış' etməyi unutmayın</p>
                <p style="color:rgb(236, 238, 118)"; class="lead">UĞURLAR!</p>
            </div>
        </div>
    </div>

{% endblock%}

templates/messages.html
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-success alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <strong>{{ message }}</strong>
        </div>
    {% endfor %}
{% endif %}