blog/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.urls import path
from home.views import home_view
from selena.views import view_404


urlpatterns = [
    path('admin/', admin.site.urls),
    # url(r'^selena/', selena_view, name='selena'),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^selena/', include('selena.urls')),
    url(r'^$', home_view, name='home'),
    #path('', home_view)
    url(r'^.*/$', view_404)
]

selena/urls.py
from .views import selena_view, selena_view1, selena_view2, selena_save, selena_delete
from django.conf.urls import url

app_name = 'selena'

urlpatterns = [
    url(r'^selenareg/$', selena_view, name='selenareg'),
    url(r'^selenaunreg/$', selena_view1, name='selenaunreg'),
    url(r'^selenagone/$', selena_view2, name='selenagone'),
    url(r'^selenasave/$', selena_save, name='selenasave'),
    url(r'^selenadelete/$', selena_delete, name='selenadelete'),
]

selena/models.py
from django.db import models

# Create your models here.

selena/forms.py
from django import forms


class SelenaForm(forms.Form):
    number = forms.CharField(max_length=7,min_length=7, label=' Abunəçinin nömrəsi ')

class SelenaForm1(forms.Form):
    ipdslam = forms.CharField(max_length=100, label=' Dslam ')
    ipplata = forms.CharField(max_length=100, label=' Plata ')
    ipport = forms.CharField(max_length=100, label=' Port ')

selena/views.py
from django.shortcuts import render, Http404, redirect
from django.http import HttpResponse
from .forms import SelenaForm
from .forms import SelenaForm1
from django.contrib import messages
from django.contrib.auth.models import User
import selenarequests as sr
import selenaunreg as su
import selenagone as sg
import selenasave as ss


def selena_view(request):
    if  not request.user.is_authenticated:
        return redirect('home')
    form = SelenaForm(request.POST or None)
    if form.is_valid():
        username = request.user.username
        u = User.objects.get(username__exact=username)
        password = u.password[8:]
        print ('  USER   : '+username)
        client_address = request.META.get('REMOTE_ADDR')
        print ('  IP     : '+client_address)
        number = form.cleaned_data.get('number')
        a=sr.sellet(username,password,number)
        if a is None:
            return render(request, 'selena/err.html')
        if len(a)==6:
            context = {
                'aa':a[0][45:],
                'bb':a[1][45:],
                'cc':a[2][45:],
                'dd':a[3][45:],
                'ee':a[4][7:23],
                }
            return render(request, 'selena/detail64active.html',context)
        if len(a)==2:
            context = {
                'aa':a[0][25:44],
                'bb':a[0][68:],
                'cc':a[1][25:44],
                'dd':a[1][68:],
                }
            return render(request, 'selena/detailadslactive.html',context)
        if len(a)==3:
            context = {
                'aa':a[0][27:50],
                'bb':a[0][52:],
                'cc':a[1][27:50],
                'dd':a[1][52:],
                }
            return render(request, 'selena/detailvdslactive.html',context)
        if len(a)==5:
            context = {
                'aa':a[0][37:],
                'bb':a[1][37:],
                'cc':a[2][37:],
                'dd':a[3][37:],
                'ee':a[4][37:],
                }
            messages.success(request, 'Fiziki Qoşulmada "SNR" Göstəriciləri Düzgün Olmaya Bilər! Baxın:"Maksimum Sürət"')
            return render(request, 'selena/detail48active.html',context)  
        if len(a)==4:
            context = {
                'aa':a[0][2:12],
                'bb':a[0][12:28],
                'cc':a[1][:16],
                'dd':a[2][:-5],
                }
            return render(request, 'selena/switchport.html',context) 
        if len(a)==7:
            context = {
                'aa':a[3],
                'bb':a[0],
                'cc':a[1],
                'dd':a[2],
                'ee':a[4],
                }
            return render(request, 'selena/switchportedge.html',context)
        else:
            context = {
                'aa':a[0],
                }
            return render(request, 'selena/detailnodsl.html',context)
    return render(request, 'selena/form.html', {'form':form})


def selena_view1(request): 
    form = SelenaForm1(request.POST or None)
    if form.is_valid():
        dslamip = form.cleaned_data.get('ipdslam')
        plataip = form.cleaned_data.get('ipplata')
        portip = form.cleaned_data.get('ipport')
        client_address = request.META.get('REMOTE_ADDR')
        print('  IP     : '+client_address)
        print('  DSLAM  : '+dslamip)
        print('  PLATA  : '+plataip)
        print('  PORT   : '+portip)
        a=su.tellet(dslamip,plataip,portip)
        if a is None:
            return render(request, 'selena/err.html')
        if len(a)==6:
            context = {
                'aa':a[0][45:],
                'bb':a[1][45:],
                'cc':a[2][45:],
                'dd':a[3][45:],
                'ee':a[4][7:23],
                }
            return render(request, 'selena/detail64active.html',context)
        if len(a)==2:
            context = {
                'aa':a[0][25:44],
                'bb':a[0][68:],
                'cc':a[1][25:44],
                'dd':a[1][68:],
                }
            return render(request, 'selena/detailadslactive.html',context)
        if len(a)==3:
            context = {
                'aa':a[0][27:50],
                'bb':a[0][52:],
                'cc':a[1][27:50],
                'dd':a[1][52:],
                }
            return render(request, 'selena/detailvdslactive.html',context)
        if len(a)==5:
            context = {
                'aa':a[0][37:],
                'bb':a[1][37:],
                'cc':a[2][37:],
                'dd':a[3][37:],
                'ee':a[4][37:],
                }
            messages.success(request, 'Fiziki Qoşulmada "SNR" Göstəriciləri Düzgün Olmaya Bilər! Baxın:"Maksimum Sürət"')
            return render(request, 'selena/detail48active.html',context)
        else:
            context = {
                'aa':a[0],
                }
            return render(request, 'selena/detailnodsl.html',context)
    return render(request, 'selena/form.html', {'form':form})


def selena_view2(request):
    if  not request.user.is_authenticated:
        return redirect('home')
    groups = request.user.groups.all()
    if groups:
        role = groups[0].name
    if role == 'Texnik':
        form = SelenaForm(request.POST or None)
        if form.is_valid():
            print ('  GROUP  : '+role)
            username = request.user.username
            u = User.objects.get(username__exact=username)
            password = u.password[8:]
            print ('  USER   : '+username)
            client_address = request.META.get('REMOTE_ADDR')
            print('  IP     : '+client_address)
            number = form.cleaned_data.get('number')
            a=sg.gellet(username,password,number)
            if a is None:
                return render(request, 'selena/errspeed.html')
            if len(a)==5:
                context = {
                    'aa':a[0][:-1],
                    'bb':a[1],
                    'cc':a[2],
                    'dd':a[3],
                    'ee':a[4][2:],
                    }
                return render(request, 'selena/detail64activespeed.html',context)
        return render(request, 'selena/formspeed.html', {'form':form})
    else:
        return render(request, 'selena/restricting.html')


def selena_save(request):
    if  not request.user.is_authenticated:
        return redirect('home')
    groups = request.user.groups.all()
    if groups:
        role = groups[0].name
    if role == 'Texnik':
        a=ss.savellet()
        print('  SAVED')
        if a is None:
            return render(request, 'selena/errspeed.html')
        else:
            f = open('resultselena.txt', 'r')
            content = f.read()
            context = {
                    'aa':content,
                    }
            f.close()
            return render(request, 'selena/resultselena.html',context)
    else:
        return redirect('home')

def selena_delete(request):
    if  not request.user.is_authenticated:
        return redirect('home')
    groups = request.user.groups.all()
    if groups:
        role = groups[0].name
    if role == 'Texnik':
        a=ss.delellet()
        return redirect('home')
    else:
        return redirect('home')



def view_404(request):
    return redirect('home')

templates/selena/detail48active.html
{% extends 'base.html' %}


{% block body %}
    <div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="thumbnail">
                <div class="caption">
                    <pre class="tab"><h5>Download Sürəti         {{ aa }} kbit/s</h5></pre>
                    <pre class="tab"><h5>Upload Sürəti           {{ bb }} kbit/s</h5></pre>
                    <pre class="tab"><h5>Download SNR'i          {{ cc }} dB</h5></pre>
                    <pre class="tab"><h5>Upload SNR'i            {{ dd }} dB</h5></pre>
                    <pre class="tab"><h5>Maksimum Sürət          {{ ee }} kbit/s</h5></pre>
                    {% if messages %}
                        {% for message in messages %}
                            <div class="alert alert-success alert-dismissible" role="alert">
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                <strong>{{ message }}</strong>
                            </div>
                        {% endfor %}
                    {% endif %}
                    {% if request.user.is_authenticated %}  
                        <a href="{% url 'selena:selenareg' %}" class="btn btn-primary" role="button">Geri</a>
                    {% else%}
                        <a href="{% url 'selena:selenaunreg' %}" class="btn btn-primary" role="button">Geri</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    </div>

{% endblock%}

templates/selena/detail64active.html
{% extends 'base.html' %}


{% block body %}
    <div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="thumbnail">
                <div class="caption">
                    <pre class="tab"><h5>Download Sürəti         {{ aa }} kbit/s</h5></pre>
                    <pre class="tab"><h5>Upload Sürəti           {{ bb }} kbit/s</h5></pre>
                    <pre class="tab"><h5>Download SNR'i          {{ cc }} dB</h5></pre>
                    <pre class="tab"><h5>Upload SNR'i            {{ dd }} dB</h5></pre>
                    <pre class="tab"><h5>MAC Adresi              {{ ee }}</h5></pre>
                    {% if request.user.is_authenticated %}  
                        <a href="{% url 'selena:selenareg' %}" class="btn btn-primary" role="button">Geri</a>
                    {% else%}
                        <a href="{% url 'selena:selenaunreg' %}" class="btn btn-primary" role="button">Geri</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    </div>

{% endblock%}

templates/selena/detail64activespeed.html
{% extends 'base.html' %}


{% block body %}
    <div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="thumbnail">
                <div class="caption">
                    <pre class="tab"><h5>Hostname : {{ aa }}</h5></pre>
                    <pre class="tab"><h5>Plate    : {{ bb }}</h5></pre>
                    <pre class="tab"><h5>Port     : {{ cc }}</h5></pre>
                    <pre class="tab"><h5>Tariff   : {{ dd }}</h5></pre>
                    <pre class="tab"><h5>Info     : {{ ee }}</h5></pre>
                    {% if request.user.is_authenticated %}  
                        <a href="{% url 'selena:selenagone' %}" class="btn btn-primary" role="button">Geri</a>
                        <a href="{% url 'selena:selenasave' %}" class="btn btn-primary" role="button">Saxla</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    </div>

{% endblock%}

templates/selena/detailadslactive.html
{% extends 'base.html' %}


{% block body %}
    <div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="thumbnail">
                <div class="caption">
                    <pre class="tab"><h5>Download Sürəti    {{ aa }}</h5></pre>
                    <pre class="tab"><h5>Upload Sürəti  {{ bb }}</h5></pre>
                    <pre class="tab"><h5>Download SNR'i   {{ cc }}</h5></pre>
                    <pre class="tab"><h5>Upload SNR'i  {{ dd }}</h5></pre>
                    {% if request.user.is_authenticated %}  
                        <a href="{% url 'selena:selenareg' %}" class="btn btn-primary" role="button">Geri</a>
                    {% else%}
                        <a href="{% url 'selena:selenaunreg' %}" class="btn btn-primary" role="button">Geri</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    </div>

{% endblock%}

templates/selena/detailnodsl.html
{% extends 'base.html' %}


{% block body %}
    <div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="thumbnail">
                <div class="caption">
                    <h4>{{ aa }}  :  DSL Yanmır</h4></p>
                    {% if request.user.is_authenticated %}  
                        <a href="{% url 'selena:selenareg' %}" class="btn btn-primary" role="button">Geri</a>
                    {% else%}
                        <a href="{% url 'selena:selenaunreg' %}" class="btn btn-primary" role="button">Geri</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    </div>

{% endblock%}

templates/selena/detailvdslactive.html
{% extends 'base.html' %}


{% block body %}
    <div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="thumbnail">
                <div class="caption">
                    <pre class="tab"><h5>Download Sürəti  {{ aa }}</h5></pre>
                    <pre class="tab"><h5>Upload Sürəti    {{ bb }}</h5></pre>
                    <pre class="tab"><h5>Download SNR'i   {{ cc }}</h5></pre>
                    <pre class="tab"><h5>Upload SNR'i     {{ dd }}</h5></pre>
                    {% if request.user.is_authenticated %}  
                        <a href="{% url 'selena:selenareg' %}" class="btn btn-primary" role="button">Geri</a>
                    {% else%}
                        <a href="{% url 'selena:selenaunreg' %}" class="btn btn-primary" role="button">Geri</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    </div>

{% endblock%}

templates/selena/err.html
{% extends 'base.html' %}


{% block body %}
    <div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="thumbnail">
                <div class="caption">
                    <h4>Yenidən yoxlayın!</h4></p>
                    {% if request.user.is_authenticated %}  
                        <a href="{% url 'selena:selenareg' %}" class="btn btn-primary" role="button">Geri</a>
                    {% else%}
                        <a href="{% url 'selena:selenaunreg' %}" class="btn btn-primary" role="button">Geri</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    </div>

{% endblock%}

templates/selena/errspeed.html
{% extends 'base.html' %}


{% block body %}
    <div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="thumbnail">
                <div class="caption">
                    <h4>Yenidən yoxlayın!</h4></p>
                    {% if request.user.is_authenticated %}  
                        <a href="{% url 'selena:selenagone' %}" class="btn btn-primary" role="button">Geri</a>
                        <a href="{% url 'selena:selenasave' %}" class="btn btn-primary" role="button">Save</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    </div>

{% endblock%}

templates/selena/form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block body %}

    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                <form method = "POST" enctype="multipart/form-data">
                    {%csrf_token%}
                    <p class="lead">Fiziki qoşulmanın yoxlanılması</p>
                    {{ form|crispy }}
                    <input class="btn btn-primary" type="submit" value="Göndər">
                </form>
            </div>
        </div>
    </div>

{% endblock%}

templates/selena/formspeed.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block body %}
    <style>
        body {
        background-color: #16b975
        }
    </style>
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                <form method = "POST" enctype="multipart/form-data">
                    {%csrf_token%}
                    <p class="lead">Porta sürət verilməsi</p>
                    {{ form|crispy }}
                    <input class="btn btn-primary" type="submit" value="Göndər">
                </form>
            </div>
        </div>
    </div>

{% endblock%}

templates/selena/restricting.html
{% extends 'base.html' %}


{% block body %}
    <div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="thumbnail">
                <div class="caption">
                    <h4>Qadağan edilmiş əməliyyat!</h4></p>
                    {% if request.user.is_authenticated %}  
                        <a href="{% url 'home' %}" class="btn btn-primary" role="button">Geri</a>
                    {% else%}
                        <a href="{% url 'home' %}" class="btn btn-primary" role="button">Geri</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    </div>

{% endblock%}

templates/selena/resultselena.html
{% extends 'base.html' %}


{% block body %}
    <div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="thumbnail">
                <div class="caption">
                    <h4>{{ aa }}</h4>
                    {% if request.user.is_authenticated %}  
                        <a href="{% url 'selena:selenadelete' %}" class="btn btn-primary" role="button">Sıfırla</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    </div>

{% endblock%}

templates/selena/switchport.html
{% extends 'base.html' %}


{% block body %}
    <div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="thumbnail">
                <div class="caption">
                    <pre class="tab"><h5> Host adı        :        {{ dd }}</h5></pre>
                    <pre class="tab"><h5>Portun Statusu   :      {{ bb }}</h5></pre>
                    <pre class="tab"><h5>MAC Adresi       :        {{ cc }}</h5></pre>
                    {% if request.user.is_authenticated %}  
                        <a href="{% url 'selena:selenareg' %}" class="btn btn-primary" role="button">Geri</a>
                    {% else%}
                        <a href="{% url 'selena:selenaunreg' %}" class="btn btn-primary" role="button">Geri</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    </div>

{% endblock%}

templates/selena/switchportedge.html
{% extends 'base.html' %}


{% block body %}
    <div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="thumbnail">
                <div class="caption">
                    <pre class="tab"><h5> Host adı        :       {{ dd }}</h5></pre>
                    <pre class="tab"><h5>Portun Statusu   :       {{ bb }}({{ ee }})</h5></pre>
                    <pre class="tab"><h5>MAC Adresi       :       {{ cc }}</h5></pre>
                    {% if request.user.is_authenticated %}  
                        <a href="{% url 'selena:selenareg' %}" class="btn btn-primary" role="button">Geri</a>
                    {% else%}
                        <a href="{% url 'selena:selenaunreg' %}" class="btn btn-primary" role="button">Geri</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    </div>

{% endblock%}